name: Build

on:
  push:
    branches:
      - main
  repository_dispatch:
      types: [compare_view_update]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          yarn install
          # update compare_view
          yarn add compare_view

      - name: Build
        run: yarn build_deploy

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: public

